"""Generic Structured Action Output Models."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ActionType(str, Enum):
    """Common semantic UI action types."""
    NAVIGATE = "NAVIGATE"
    CLICK_BUTTON = "CLICK_BUTTON"
    SET_INPUT_VALUE = "SET_INPUT_VALUE"
    TOGGLE_SWITCH = "TOGGLE_SWITCH"
    SELECT_OPTION = "SELECT_OPTION"
    OPEN_MODAL = "OPEN_MODAL"
    CLOSE_MODAL = "CLOSE_MODAL"
    FILTER_TABLE = "FILTER_TABLE"
    RESET_FILTERS = "RESET_FILTERS"
    NOTIFY_USER = "NOTIFY_USER"
    CUSTOM = "CUSTOM"


class UIAction(BaseModel):
    """A discrete, semantic UI mutation commanded by the Voice AI Copilot."""
    action_type: ActionType = Field(..., description="The semantic action type to execute")
    target_id: Optional[str] = Field(
        None,
        description="Semantic ID of the target UIComponent (e.g. 'theme_toggle', 'filter_region')"
    )
    payload: Dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters for the action (e.g., {'value': 'Production'})"
    )
    description: str = Field(
        ...,
        description="Human-readable explanation of what this action achieves in the UI"
    )


class AgentResponse(BaseModel):
    """Complete structured response generated by the Agent for a user interaction."""
    thought: str = Field(
        ...,
        description="Internal chain-of-thought explaining how the agent mapped user intent to ViewContext actions"
    )
    speech_output: str = Field(
        ...,
        description="Spoken text to be synthesized via TTS and streamed back to the user"
    )
    actions: List[UIAction] = Field(
        default_factory=list,
        description="Ordered sequence of semantic UI actions to execute on the frontend"
    )
    status: str = Field(
        "success",
        description="Status indicator: 'success', 'need_more_info', 'action_not_supported', 'error'"
    )
